baseURL = 'https://zenicity.github.io'
languageCode = 'en-us'
title = 'Yokoso'
theme = 'm10c'
[params]
  author = "Varun Subramanian"
  description = "I publish different malware reports."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/zenicity"
  [[params.social]]
    icon = "twitter"
    name = "twitter"
    url = "https://twitter.com/varam1203"
